# Generated by Django 3.1.2 on 2021-02-03 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ptf', '0003_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='firstname',
            new_name='name',
        ),
    ]
