# Generated by Django 3.1.2 on 2021-02-03 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ptf', '0004_auto_20210203_2012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='firstname',
        ),
    ]
