# Generated by Django 3.1.2 on 2021-02-04 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptf', '0005_auto_20210203_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='aboutservice',
            field=models.CharField(max_length=5000),
        ),
    ]
