# Generated by Django 3.1.2 on 2021-02-21 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptf', '0006_auto_20210204_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aboutm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to='ptf/images')),
                ('brief', models.CharField(max_length=50)),
                ('education', models.CharField(max_length=50)),
            ],
        ),
    ]
