# Generated by Django 3.1.2 on 2021-02-21 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptf', '0007_aboutm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutm',
            name='brief',
            field=models.CharField(max_length=500),
        ),
    ]
