# Generated by Django 3.1.2 on 2021-02-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptf', '0009_auto_20210221_2335'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postcmnt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
