# Generated by Django 3.1.2 on 2021-02-23 15:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ptf', '0011_postcmnt_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcmnt',
            name='date',
        ),
        migrations.AddField(
            model_name='postcmnt',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
