# Generated by Django 3.1.2 on 2021-02-26 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ptf', '0014_auto_20210226_1016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcmnt',
            old_name='mssg',
            new_name='msg',
        ),
    ]
